services:
  adminer:
    container_name: 'da50-filegenie-adminer'
    image: 'adminer:latest'
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - appli

  mysql:
    container_name: 'da50-filegenie-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=filegenie'
      - 'MYSQL_PASSWORD=user'
      - 'MYSQL_ROOT_PASSWORD=user'
      - 'MYSQL_USER=user'
    ports:
      - '0:3306'
    networks:
      - appli

networks:
  appli:
    driver: bridge




